config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  
  root 'items#index'
  resources :users, only: [:show , :index] do
    collection do
      get 'logout'
    end
    member do
      get 'favorite'
    end
  end

  resources :items, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: :index do
      member do
        get 'buy'
        post 'pay'
      end
    end
  end
  
  resources :cards, only: [:new, :create, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end
  resources :categories ,only: [:show, :index]
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  belongs_to :saler, class_name: "User", optional: true
  belongs_to :buyer, class_name: "User", optional: true
  
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  validates_associated :images
  validates :images, presence: true , length: { maximum: 10 ,message: "は10枚以内にしてください"}

  belongs_to :category

  belongs_to :brand ,optional: true 
  accepts_nested_attributes_for :brand

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  validates :name, presence: true, length:  { maximum: 40 }
  
  validates :description, presence: true, length:  { maximum: 1000 }

  validates :status,:cost, :days,:prefecture_id, presence: true

  validates :price, presence: true,
  numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 ,allow_blank: true}
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :item_params, only: :create
  before_action :set_item, except: [:index, :new, :create,:get_category_children,:get_category_grandchildren]

  def index
    @items = Item.all.order("created_at DESC")
  end

  def new
    @item = Item.new
    @item.build_brand
    @item.images.new
    #セレクトボックスの初期値設定
    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end
  
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end



  def show
    @item = Item.find(params[:id])
    @items = Item.all
  end

  def create
    @item = Item.new(item_params)
    if @item.valid?
      @item.save
      redirect_to root_path
    else
      #セレクトボックスの初期値設定
    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
      @item.images.new
      render :new
    end
  end

  def buy
    if card.exists?
      @card     = Card.find_by(user_id: current_user.id)
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = Payjp::Customer.retrieve(@card.customer_id).cards.data[0]
    end
  end

  def pay
    @card = Card.find_by(user_id: current_user.id)
    @item.save!
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
    @charge = Payjp::Charge.create(
    amount: @product.price,
    customer: @card.customer_id,
    currency: 'jpy'
    )
  end

  def edit
    if user_signed_in? && current_user.id == @item.saler_id
      grandchild_category = @item.category
      child_category = grandchild_category.parent

      @category_parent_array = Category.where(ancestry: nil).pluck(:name,:id)
      
      @category_children_array = Category.where(ancestry: child_category.ancestry).pluck(:name,:id)

      @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry).pluck(:name,:id)
      # grandchild_category = @item.category
      # child_category = grandchild_category.parent
  
  
      # @category_parent_array = []
      # Category.where(ancestry: nil).each do |parent|
      #   @category_parent_array << parent.name
      # end
  
      # @category_children_array = []
      # Category.where(ancestry: child_category.ancestry).each do |children|
      #   @category_children_array << children
      # end
  
      # @category_grandchildren_array = []
      # Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      #   @category_grandchildren_array << grandchildren
      # end
    else 
      @items = Item.all
      render :index
    end
  end

  def update
    if @item.update(item_params)
      session.delete(:error)
      redirect_to root_path
    else
      session[:error] = @item.errors.full_messages
      redirect_to action: :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :category_id, :status, :cost, :prefecture_id, :days, :price, images_attributes: [:url, :_destroy, :id], brand_attributes: [:name],).merge(user_id: current_user.id).merge(saler_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
    @items = Item.all
    @items = Item.includes(:images, :brands)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_items-footer.html.haml
%footer.item-footer
  %ul
    %li 
      = link_to 'プライバシーポリシー', "#"
    %li 
      = link_to 'フリマ利用規約', "#"
    %li 
      = link_to '特定商品取引に関する表記', "#"
  .footer-logo
    = link_to root_path do
      = image_tag "/material/logo/logo.png", class: "furima-image" 
  .footer-name 
    ©︎ FURIMA

app/views/items/_items-header.html.haml
.item-header
  = link_to root_path do
    = image_tag "/material/logo/logo-white.png"  , size: "270x60"

app/views/items/_items-link.html.haml
.item__index--main
  %section.bottom-donwnload
    .bottom-donwnload__inner
      %h2.bottom-donwnload__inner__title
        だれでもかんたん、人生を変えるフリマアプリ
      %p.bottom-donwnload__inner__text
        今すぐ無料ダウンロード！
      .bottom-donwnload__inner__icon
        = link_to 'https://www.apple.com/jp/ios/app-store/',class:'a-btn' do
          = image_tag "/material/Download_on_the_App_Store_Badge.svg" 
        = link_to 'https://play.google.com/store/apps',class:'g-btn' do
          = image_tag "/material/Download_on_the_Google_Play_Badge.svg" 

app/views/items/_items-main.html.haml
.items-main
  .items-main__name
    = @item.name
  -# .items-main__description

  .items-main__image
    - @item.images.each do | image |
      = image_tag image.url.url

  %table.items-main__detail
    %tbody
      %tr
        %th
          出品者
        %td
          = @item.user.nickname
      %tr
        %th
          カテゴリー
        %td
          = @item.category.name

      %tr
        %th
          ブランド
        %td
          = @item.brand.name
      %tr
        %th
          商品の状態
        %td
          = @item.status
      %tr
        %th
          配送料の負担
        %td
          - if @item.cost == 1
            着払い

          - else
            出品者負担
          
      %tr
        %th
          配送元地域
        %td
          = @item.prefecture.name
      %tr
        %th
          発送日の目安
        %td
          = @item.days
          
  .items-main__select                                    
  .items-main__price
    ¥
    %span.items-main__price--realmoney
      = @item.price
    %span.items-main__price--tax
      (税込み)
    %span.items-main__price--shipping-fee
      送料込み

- if user_signed_in? && current_user.id == @item.user_id

- else
  .items-main__buy--btn
    = link_to "購入画面に進む", buy_item_purchase_path(@item.id), class: "buy-box" 
.items-main__description-inner
  = @item.description
.items-main__button
  .items-main__button--left
    .items-main__button--left--left
      %i.far.fa-heart
      いいね！
    .items-main__button--left--right  
      不適切な商品報告
  .items-main__button--right
    安心・安全への取り組み

- if user_signed_in? && current_user.id == @item.user_id
  = link_to edit_item_path , class: "items-main__button__edit-btm" do 
    編集する
  = link_to item_path , method: :delete , class:"items-main__button__destroy-btm" do
    削除する

app/views/items/_items-social-media.html.haml
.items-social-media
  %ul.items-social-media__box
    %li
      = link_to "https://www.facebook.com/", class: "link--facebook" do
        %i.fab.fa-facebook-square
    %li
      = link_to "https://twitter.com/", class: "link--twitter" do
        %i.fab.fa-twitter-square
    %li
      = link_to "https://line.me/ja/", class: "link--line" do
        %i.fab.fa-line
    %li
      = link_to "https://www.pinterest.jp/", class: "link--pinterest" do
        %i.fab.fa-pinterest-square

app/views/items/_items-sub.html.haml
.items-sub--main__production--box
  .items-sub--main__production--box--contents
    = image_tag "/material/pict/焼きサンマ.png", class: "imagesample2"
  .items-sub--main__production--box--body
    .items-sub--main__production--box--body--name
      Tシャツ
    .items-sub--main__production--box--body--price
      .items-sub--main__production--box--body--price--money
        .div
          .div
            ¥400
          .div
            (税込み)
        .div
          %i.far.fa-heart
          0
      

app/views/items/buy.html.haml
.kounyu-all
  = render "layouts/header"
  .kounyu-main
    .kounyu-main__box-1 商品購入の確認
    .kounyu-main__box-2
      .kounyu-main__box-2__item-box
        .kounyu-main__box-2__item-box__pic
          = image_tag "/material/pict/pict-reason-02.jpg" ,  size: "80x80"
        .kounyu-main__box-2__item-box__text
          .kounyu-main__box-2__item-box__text__name 謎の物体
          .kounyu-main__box-2__item-box__text__price
            .kounyu-main__box-2__item-box__text__price__nedan ￥99999 (税込み)
            .kounyu-main__box-2__item-box__text__price__souryou 送料込み
    -# これより下の記述はフォーム      
    .kounyu-main__box-v2
      .kounyu-main__box-v2__box-3 
        .kounyu-main__box-v2__box-3__kingaku  支払い金額
        .kounyu-main__box-v2__box-3__price  ¥3,000
      .kounyu-main__box-v2__box-4
        .kounyu-main__box-v2__box-4__siharaihouhou 支払い方法
        = link_to "#", class: "kounyu-main__box-v2__box-4__henkousuru" do 
          .kounyu-main__box-v2__box-4__henkousuru 変更する
      .kounyu-main__box-v2__box-5
        .kounyu-main__box-v2__box-5__kureka クレジットカード
        .kounyu-main__box-v2__box-5__number
          = "**** **** **** " + "#{@default_card_information.last4}"
        .kounyu-main__box-v2__box-5__yuukoukigen 有効期限  12/21
      .kounyu-main__box-v2__box-6
        .kounyu-main__box-v2__box-6__haisou
          .kounyu-main__box-v2__box-6__haisou__haisousaki 配送先
          = link_to "#", class: "kounyu-main__box-v2__box-4__henkousuru" do 
            .kounyu-main__box-v2__box-6__haisou__henkou  変更する
        .kounyu-main__box-v2__box-6__adress
          %div.bababa 〒787-7435
          %div.bababa 大阪府山田市ウエフォン町
          %div.bababa 鈴木一郎
      .kounyu-main__box-v2__box-7
        .kounyu-main__box-v2__box-7__tyuui 郵便局/コンビニ受取をご希望の方は、購入後に取引画面から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
        .kounyu-main__box-v2__box-7__bottun
          .kounyuusuru 購入する
          -# = f.submit '購入する', class: "kounyuusuru"        
= render "items-link"
= render "layouts/footer"

app/views/items/edit.html.haml
= render partial: 'items/items-header'

.item-main
  .item-main__box

    - if session[:error].present?
      %ul.item-errors
        入力内容に誤りがあります
        - session[:error].each do |e|
          %li= e

    = form_for @item do |f|

      .item-main__box__pic
        .title
          出品画像
          %span.require 必須
        .item-main__box__pic__picture__upload-text 
          最大10枚までアップロードできます。
          -# .item-main__box__pic__picture__upload-form 
          -#   %input.gazoutoukou{:accept => "image/png,image/jpeg", :autocomplete => "off", :multiple => "multiple", :style => "display:none", :tabindex => "-1", :type => "file"}/
          -#   %svg.sc-hkbPbT.lodtkW{"aria-hidden" => "true", :fill => "#222222", "fill-rule" => "evenodd", :height => "24", :viewbox => "0 0 24 24", :width => "24"}
          -#   %path{:d => "M19.3,5H16.73l-.8-1.61A.7.7,0,0,0,15.3,3H8.7a.7.7,0,0,0-.63.39L7.27,5H4.7A2.7,2.7,0,0,0,2,7.7V18.3A2.7,2.7,0,0,0,4.7,21H19.3A2.7,2.7,0,0,0,22,18.3V7.7A2.7,2.7,0,0,0,19.3,5ZM12,17.3A4.3,4.3,0,1,1,16.3,13,4.31,4.31,0,0,1,12,17.3Z"}
          -#   %p.sc-hcnlBt.kuVoVA
          #image-box
            #previews
              - if @item.persisted?
                - @item.images.each_with_index do |image, i|
                  = image_tag image.url.url, data: { index: i }, width: "110px", height: "110px"
            = f.fields_for :images do |image|
              .js-file_group{"data-index": "#{image.index}"}
                = image.file_field :url, class: 'js-file'
                %span.js-remove
                  削除
              - if @item.persisted?
                = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
            - if @item.persisted?
              .js-file_group{"data-index": "#{@item.images.count}"}
                = file_field_tag :url, name: "item[images_attributes][#{@item.images.count}][url]", class: 'js-file'
                %span.js-remove
                  削除

      .item-main__box__name
        %span.title 商品名
        %span.require 必須
        = f.text_field :name, class: "input", placeholder: "40文字まで"

      .item-main__box__description
        %span.title 商品の説明
        %span.require 必須
        = f.text_area :description, class:"form-description", placeholder: "商品の説明（必須 1,000文字以内）\n（色、素材、重さ、定価、注意点など）\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。\n          ", rows: "7"

      .item-main__box__item-info
        商品の詳細

        .item-main__box__item-info__category
          %span.title カテゴリー
          %span.require 必須
          .listing-select-wrapper
            .listing-select-wrapper__box
              -# = f.select :category_id, @category_parent_array, {selected:@item.category.parent.parent.name}, { class: 'listing-select-wrapper__box--select', id: 'parent_category'}
              = f.select :category_id, options_for_select(@category_parent_array.map{|b|[b[0], b[0]]}, @item.category.parent.parent.name),{}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
          .listing-select-wrapper__added#children_wrapper
            .listing-select-wrapper__box
              -# = f.select :category_id, @category_children_array, {selected:@item.category.parent.id}, { class: 'listing-select-wrapper__box--select', id: 'child_category'}
              = f.select :category_id, options_for_select(@category_children_array.map{|b| [b[0], b[1], {data:{category: b[1]}}]}, @item.category.parent.id),{}, {class: 'listing-select-wrapper__box--select', id: 'child_category'}
          .listing-select-wrapper__added#grandchildren_wrapper
            .listing-select-wrapper__box
              -# = f.select :category_id, @category_grandchildren_array, {selected:@item.category.id}, { class: 'listing-select-wrapper__box--select', id: 'grandchild_category'}
              = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b[0], b[1], {data:{category: b[1]}}]}, @item.category.id ),{}, {class: 'listing-select-wrapper__box--select', id: 'grandchild_category'}

        .item-main__box__item-info__bland
          %span.title ブランド
          %span.any 任意
          = f.fields_for :brand do |brand| 
            = brand.text_field :name, placeholder: "例 （シャネル）", class:"input"

        .item-main__box__item-info__status
          %span.title 商品の状態
          %span.require 必須
          = f.select :status,[["新品、未使用", "新品、未使用"],["未使用に近い", "未使用に近い"],["目立った傷や汚れなし", "目立った傷や汚れなし"],["やや傷や汚れあり", "やや傷や汚れあり"],["傷や汚れあり", "傷や汚れあり"],["全体的に状態が悪い", "全体的に状態が悪い"]], { include_blank: "選択してください"} , class:"input"

      .item-main__box__delivery
        配送について

        .item-main__box__delivery__cost
          %span.title 配送料の負担
          %span.require 必須
          = f.select :cost,[["着払い(購入者負担)", 1],["送料込み(出品者負担)", 2]], { include_blank: "選択してください"}, class:"input"

        .item-main__box__delivery__prefecture
          %span.title 発送元の地域
          %span.require 必須
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt:"選択してください"}, class:"input"

        .item-main__box__delivery__days
          %span.title 発送までの日数
          %span.require 必須
          = f.select :days,[["1~2日で発送", "1~2日で発送"],["2~3日で発送", "2~3日で発送"],["4~7日で発送", "4~7日で発送"]], { include_blank: "選択してください"}, class:"input"

      .item-main__box__price
        .title-box
          %span.title 販売価格（¥300〜9,999,999）
          %span.require 必須
        %span ¥
        = f.number_field :price ,class:"input-price"

      .item-main__box__submit
        = f.submit :編集する, class:"submit-btn"

= render partial: 'items/items-footer'

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/index.html.haml
= render partial: 'layouts/header'

.item__index--main

  %section.first-view
    .first-view__content
      %h2.first-view__content__title
        %br 人生を変えるフリマアプリ
      %p.first-view__content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br フリマアプリです
      .first-view__content__btn
        = link_to 'https://www.apple.com/jp/ios/app-store/',class:'a-btn' do
          = image_tag "/material/Download_on_the_App_Store_Badge.svg" 
        = link_to 'https://play.google.com/store/apps',class:'g-btn' do
          = image_tag "/material/Download_on_the_Google_Play_Badge.svg" 

  %section.indroduction
    %h2.indroduction__title
      FURIMAが選ばれる3つの理由
    %ul.indroduction__lists
      %li.indroduction__lists__list
        .indroduction__lists__list__pict
          %span.number 1
          = image_tag "/material/pict/pict-reason-01.jpg" , size: "306x306"
        %h3.indroduction__lists__list__text
          %span 3分
          ですぐに出品
        %p.indroduction__lists__list__description
          スマホで入力するだけで簡単に出品できる！
      %li.indroduction__lists__list
        .indroduction__lists__list__pict
          %span.number 2
          = image_tag "/material/pict/pict-reason-02.jpg" , size: "306x306"
        %h3.indroduction__lists__list__text
          %span シンプル
          で使いやすい
        %p.indroduction__lists__list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.indroduction__lists__list.list--last
        .indroduction__lists__list__pict
          %span.number 3
          = image_tag "/material/pict/pict-reason-03.jpg" , size: "306x306"
        %h3.indroduction__lists__list__text
          手数料
          %span 業界最安
        %p.indroduction__lists__list__description
          最大3%でお得に出品&amp;購入！

  %section.middle-download
    .middle-download__inner
      %h2.middle-download__inner__title
        会員数日本一位
      %p.middle-download__inner__text
        FURIMAは、フリマアプリで最も人気。
        %br 出品・購入回数も業界最多です！
        ほしかったあの商品に出会えるかもしれません。
      .middle-download__inner__btn
        = link_to 'https://www.apple.com/jp/ios/app-store/',class:'a-btn' do
          = image_tag "/material/Download_on_the_App_Store_Badge.svg" 
        = link_to 'https://play.google.com/store/apps',class:'g-btn' do
          = image_tag "/material/Download_on_the_Google_Play_Badge.svg" 

  %section.feature 
    %h2.feature__header
      FURIMAの特徴
    .feature__items
      %section.feature__items__item
        %figure.feature__items__item__img
          = image_tag "/material/icon/icon-01.png" 
        %h3.feature__items__item__title
          簡単に売り買いできる
        %p.feature__items__item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.feature__items__item
        %figure.feature__items__item__img
          = image_tag "/material/icon/icon-03.png" 
        %h3.feature__items__item__title
          売上金は即日振込み対応
        %p.feature__items__item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %section.feature__items__item
        %figure.feature__items__item__img
          = image_tag "/material/icon/icon-04.png" 
        %h3.feature__items__item__title
          様々な支払いに対応
        %p.feature__items__item__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.pickup
    %h2.pickup__header
      ピックアップカテゴリー
    .pickup__box
      .pickup__box__header
        = link_to '#' do
          %h3
            新規投稿商品
      .pickup__box__lists
        - @items.each do |item|
          -if item.buyer_id.nil? 

            .pickup__box__lists__list
              = link_to item_path(item.id) do
                %figure.pickup__box__lists__list__img
                  = image_tag item.images.first.url.url
                .pickup__box__lists__list__body
                  %h3.pickup__box__lists__list__body__name
                    = item.name
                  .pickup__box__lists__list__body__details
                    %ul
                      %li
                        = item.price
                      %li
                        ★0
                    %p 
                      (税込)

  %section.pickup
    %h2.pickup__header
      ピックアップブランド
    .pickup__box
      .pickup__box__header
        = link_to '#' do
          %h3
            アーカイバ

      .pickup__box__lists
        .pickup__box__lists__list
          = link_to '#' do
            %figure.pickup__box__lists__list__img
              = image_tag "/material/pict/pict-reason-02.jpg" ,  size: "220x150"
            .pickup__box__lists__list__body
              %h3.pickup__box__lists__list__body__name
                さんま
              .pickup__box__lists__list__body__details
                %ul
                  %li
                    300円
                  %li
                    ★0
                %p 
                  (税込)

        .pickup__box__lists__list
          = link_to '#' do
            %figure.pickup__box__lists__list__img
              = image_tag "/material/pict/pict-reason-02.jpg" ,  size: "220x150"
            .pickup__box__lists__list__body
              %h3.pickup__box__lists__list__body__name
                さんま
              .pickup__box__lists__list__body__details
                %ul
                  %li
                    300円
                  %li
                    ★0
                %p 
                  (税込)

        .pickup__box__lists__list
          = link_to '#' do
            %figure.pickup__box__lists__list__img
              = image_tag "/material/pict/pict-reason-02.jpg" ,  size: "220x150"
            .pickup__box__lists__list__body
              %h3.pickup__box__lists__list__body__name
                さんま
              .pickup__box__lists__list__body__details
                %ul
                  %li
                    300円
                  %li
                    ★0
                %p 
                  (税込)

  %section.bottom-donwnload
    .bottom-donwnload__inner
      %h2.bottom-donwnload__inner__title
        だれでもかんたん、人生を変えるフリマアプリ
      %p.bottom-donwnload__inner__text
        今すぐ無料ダウンロード！
      .bottom-donwnload__inner__icon
        = link_to 'https://www.apple.com/jp/ios/app-store/',class:'a-btn' do
          = image_tag "/material/Download_on_the_App_Store_Badge.svg" 
        = link_to 'https://play.google.com/store/apps',class:'g-btn' do
          = image_tag "/material/Download_on_the_Google_Play_Badge.svg" 


=link_to new_item_path , class:'purchaseBtn' do
  %span.purchaseBtn__text 出品する
  =image_tag "/material/icon/icon_camera.png" 

= render partial: 'layouts/footer'

app/views/items/show.html.haml
= render "layouts/header"
.items
  = render "items-main"
%form.items-comment
  %input.items-comment--text{type: "textarea"}
  .realmessage
    相手のことを考え丁寧なコメントを心がけましょう。
    %br
    不快な言葉遣いなどは利用制限や退会処分となる事があります。
  %button.items-comment--btn{type: "submit"}
    %i.fa.fa-comment
    コメントする
= render "items-social-media"
.items-sub
  .items-sub--main
    .items-sub--main__header
      #{@item.user.nickname}さんのその他の出品
    .items-sub--main__production
      = render "items-sub"
      = render "items-sub"
      = render "items-sub"
  .items-sub--main
    .items-sub--main__header
      ユニクロのTシャツ/カットソー(半袖/袖なし) その他の商品
    .items-sub--main__production
      = render "items-sub"
      = render "items-sub"
      = render "items-sub"
    -#   = render "items-sub"
= render "items-link"
= render "layouts/footer"

    
  