config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  
  root 'items#index'
  resources :users, only: [:show , :index] do
    collection do
      get 'logout'
    end
    member do
      get 'favorite'
    end
  end

  resources :items, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: :index do
      member do
        get 'buy'
        post 'pay'
      end
    end
  end
  
  resources :cards, only: [:new, :create, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end
  resources :categories ,only: [:show, :index]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  def new
    card = Card.where(user_id: current_user.id)
    redirect_to card_path(current_user.id) if card.exists?
  end

  def create
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
    if params['payjp-token'].blank?
      redirect_to new_card_path
    else
      customer = Payjp::Customer.create(
        email: current_user.email,
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_path(current_user.id)
      else
        redirect_to action: "create"
      end
    end
  end

  def destroy
    @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      if @card.destroy
      else
        redirect_to card_path(current_user.id), alert: "削除できませんでした。"
      end
    end
  end

  def show
    @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to new_card_path
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @card_brand = @customer_card.brand
      case @card_brand
      when "Visa"
        @card_src = "visa.png"
      when "JCB"
        @card_src = "jcb.png"
      when "MasterCard"
        @card_src = "master.png"
      when "American Express"
        @card_src = "amex.png"
      when "Diners Club"
        @card_src = "diners.png"
      when "Discover"
        @card_src = "discover.png"
      end
      @exp_month = @customer_card.exp_month.to_s
      @exp_year = @customer_card.exp_year.to_s.slice(2,3)
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/destroy.html.haml
= render "layouts/header"
.destoroy
  .destoroy__frame
    .destoroy__frame__message
      削除が完了しました。
    %ul.destoroy__frame__btns
      %li.card_new_link
        = link_to "クレジットカード新規登録", new_card_path, class: "credit_card_new_link__btn"
      %li.my_page_link
        = link_to "マイページに戻る", user_path(current_user.id), class: "my_page_link__btn"
= render "layouts/footer"

app/views/cards/new.html.haml
= render "layouts/header"
.show-cards-wrapper
  .card-wrapper
    .card-wrapper__title 
      クレジットカード情報入力
    = form_tag(cards_path, method: :post, id: "charge-form", name: "inputForm") do
      .card-wrapper__content-number
        カード番号
        %span{class: "required"}
          必須
      = text_field_tag 'payment_card_no', "", class: 'card-wrapper__input', id: "payment_card_no", placeholder: '半角数字のみ', type: "text", maxlength: "16"
    .card-wrapper__image
      = image_tag(image_path('cards/visa.png'), class: 'visa')
      = image_tag(image_path('cards/master.png'), class: 'master')
      = image_tag(image_path('cards/jcb.png'), class: 'jcb')
      = image_tag(image_path('cards/amex.png'), class: 'amex')
      = image_tag(image_path('cards/diners.png'), class: 'diners')
      = image_tag(image_path('cards/discover.png'), class: 'discover')

    
    .card-wrapper__content-number
      有効期限
      %span{class: "required"}
        必須
    .card-wrapper__input__input-num
      .month
        %select#payment_card_month.card-default{name: "payment_card_month", type: "text"}
          %option{value: "1"} 01
          %option{value: "2"} 02
          %option{value: "3"} 03
          %option{value: "4"} 04
          %option{value: "5"} 05
          %option{value: "6"} 06
          %option{value: "7"} 07
          %option{value: "8"} 08
          %option{value: "9"} 09
          %option{value: "10"} 10
          %option{value: "11"} 11
          %option{value: "12"} 12
        .month-details 
          月
      .year
        %select#payment_card_year.card-default{name: "payment_card_year", type: "text"}
          %option{value: "2020"} 20
          %option{value: "2021"} 21
          %option{value: "2022"} 22
          %option{value: "2023"} 23
          %option{value: "2024"} 24
          %option{value: "2025"} 25
          %option{value: "2026"} 26
          %option{value: "2027"} 27
          %option{value: "2028"} 28
          %option{value: "2029"} 29
          %option{value: "2030"} 30
        .year-details
          年
    .card-wrapper__content-number
      セキュリティコード
      %span{class: "required"}
        必須
    .card-wrapper__cardsecurity
      = text_field_tag  "payment_card_cvc", "", type: 'text', class: 'card-wrapper__cardsecurity__form', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面4桁もしくは3桁の番号'
    .add
    = submit_tag "登録", class: "submit-btn", id: "payment_card_submit-button"
= render "layouts/footer"

app/views/cards/show.html.haml
= render 'layouts/header'

- breadcrumb :user_card, current_user
= render "layouts/breadcrumbs"

.show-card-wrapper
  = render "layouts/content"
  .card-wrapper2
    .card-wrapper2__title
      支払い方法
    .card-wrapper2__list
      .card-wrapper2__list__title
        クレジットカード一覧
      .card-wrapper2__list__frame
        .card-wrapper2__info
          .card-wrapper2__info__brand
            = image_tag "cards/#{@card_src}", class: "credit_card_info__brand__img", alt: @card_brand
          .card-wrapper2__info__numbers
            .number
              = "**** **** **** " + @customer_card.last4
            .expiration-date__title
              有効期限
            .expiration_date__info
              = @exp_month + "月 / " + @exp_year+ "年 " 
        .destroy__function
          .destroy__function__link
            = link_to card_path, method: :delete, class: "destroy__btn" do 
              削除する
      .payment-details
        = link_to "支払い方法について >", "", class: "payment-details__btn"
= render 'layouts/footer'