config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  
  root 'items#index'
  resources :users, only: [:show , :index] do
    collection do
      get 'logout'
    end
    member do
      get 'favorite'
    end
  end

  resources :items, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: :index do
      member do
        get 'buy'
        post 'pay'
      end
    end
  end
  
  resources :cards, only: [:new, :create, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end
  resources :categories ,only: [:show, :index]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
  # validates :name, presence: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @parents = Category.where(ancestry: nil)
  end

  def show
    @category = Category.find(params[:id])
    @parents = Category.where(ancestry: nil)

    anc = @category.ancestry
    match_id = []

    if anc.blank?  #親カテゴリーの抽出
      anc_set ="^#{@category.id}/"
      reg = Regexp.new(anc_set)
      not_null_categories = Category.where.not("ancestry IS NULL")
      not_null_categories.each do |c|
        if c[:ancestry].match(reg)
          match_id << c.id
        end
      end
      @items = Item.where(category_id: match_id)
    elsif anc.match(/\//)  #孫カテゴリーの抽出
      @items = Item.where(category_id: @category.id)
    else
      parent = anc
      child = @category_id
      anc_set = "#{parent}/#{child}"
      Category.all.each do |c|
        if c[:ancestry] == anc_set
          match_id << c.id
        end
      end
      @items = Item.where(category_id: match_id)
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.haml
= render "layouts/header"
- breadcrumb :categories ,@category
= render "layouts/breadcrumbs"

.category
  .category__header
    カテゴリー 一覧
  .category__main
    -@parents.each do |parent|
      .parent
        = link_to category_path(parent.id) do
          = parent.name
      .child-wrapper
        - parent.children.each do |child|
          .child-granchild-wrapper
            .child
              = link_to category_path(child.id) do
                =child.name 
            .grandchild-wrapper
              - child.children.each do |grandchild|
                .grandchild
                  = link_to category_path(grandchild.id) do
                    =grandchild.name
= render "layouts/footer"

app/views/categories/show.html.haml
= render "layouts/header"
- breadcrumb :category ,@category
= render "layouts/breadcrumbs"

.category
  .category__header
    #{@category.name}の商品一覧
  .category__items
    - if @items.blank?
      .no-item
        お探しの商品は出品されておりません
    -else
      - @items.each do |item|
        -if item.buyer_id.nil? 
          .category__items__item
            = link_to item_path(item.id) do
              %figure.category__items__item__img
                = image_tag item.images.first.url.url
              .category__items__item__body
                %h3.category__items__item__body__name
                  = item.name
                .category__items__item__body__details
                  %ul
                    %li
                      = item.price
                    %li
                      ★0
                  %p 
                  (税込)
= render "layouts/footer"