config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end

  
  root 'items#index'
  resources :users, only: [:show , :index] do
    collection do
      get 'logout'
    end
    member do
      get 'favorite'
    end
  end

  resources :items, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: :index do
      member do
        get 'buy'
        post 'pay'
      end
    end
  end
  
  resources :cards, only: [:new, :create, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end
  resources :categories ,only: [:show, :index]
end

app/views/layouts/_breadcrumbs.html.haml
.breadcrumbs
  = breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-list"

app/views/layouts/_content.html.haml
- contents = ['マイページ', 'いいね！一覧', '出品する', '出品した商品-出品中', '出品した商品-売却済み', '購入した商品-過去の取引', 'プロフィール', '発送元・お届け先住所変更', '支払い方法', 'メール/パスワード', 'ログアウト']
- mypagelinks = [user_path(current_user),favorite_user_path(current_user), new_item_path,'', '', '', '', '', card_path(current_user), '', logout_users_path(current_user)]

.show-users-wrapper__center__left-content
  - contents.each.with_index(0) do |content, i|
    = link_to mypagelinks[i],class: "show-users-wrapper__center__left-content__box" do
      = content

app/views/layouts/_footer.html.haml
.footer
  %ul.contents
    %li.content
      .content__head
        FURIMAについて
      %ul
        %li
          = link_to '#' do
            会社概要（運営会社）
        %li
          = link_to '#' do
            プライバシーポリシー
        %li
          = link_to '#' do
            FURIMA利用規約
        %li
          = link_to '#' do
            ポイントに関する規約
    %li.content
      .content__head
        FURIMAを見る
      %ul
        %li
          = link_to categories_path do
            カテゴリー一覧
        %li
          = link_to '#' do
            ブランド一覧
    %li.content
      .content__head
        ヘルプ＆ガイド
      %ul
        %li
          = link_to '#' do
            FURIMAガイド
        %li
          = link_to '#' do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to '#' do
            お知らせ
  .footer__logo
    = link_to root_path do
      = image_tag "/material/logo/logo-white.png", class: "furima-image"
  .footer__name
    ©︎ FURIMA

app/views/layouts/_header.html.haml
%header.pc-header
  .header--inner
    .header--inner__main
      %h1.header--inner__main__icon
        = link_to root_path do
          = image_tag "/material/logo/logo.png" 
      .header--inner__main__search-box
        %form
          %input{ placeholder:'キーワードから探す' }
          %button 
            .search-box__icon
              = image_tag "/material/icon/icon-search 1.png" 
    .header--inner__nav
      %ul.header--inner__nav__left
        %li.header--inner__nav__left--category
          =link_to categories_path do
            カテゴリー
        %li.header--inner__nav__left--brand
          ブランド
      %ul.header--inner__nav__right
        -if user_signed_in?
          %li
            = link_to  user_path(current_user.id) do
              マイページ
        -else
          %li.header--inner__nav__right--login
            = link_to  new_user_session_path do
              ログイン
          %li.header--inner__nav__right--registration
            = link_to new_user_registration_path do
              新規会員登録

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SampleMarket
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield